### ISSUE TITLE
Sample Client application

### ISSUE THREAD

**Issue by JensWinter** [moooink/loopback-component-satellizer#14]
Is there a sample application of a client that demonstrates how to use that library.
I'm still having difficulties here.

Thanks in advance!

Best regards,
Jens

**Comment by jdrouet** [comment]
You can use the example from the Satellizer repository (https://github.com/sahat/satellizer) but if you use the loopback angular sdk and the embedded authentication, you have to take care about the localstorage keys used by the LoopBackAuth service and Satellizer

**Comment by doktordirk** [comment]
i'm working on an aurelia client https://github.com/doktordirk/aurelia-auth-loopback-sample
