### ISSUE TITLE
Probleme with Token generation

### ISSUE THREAD

**Issue by thugyac** [moooink/loopback-component-satellizer#16]
Hello, 

I'm trying to add the Thrid Party authentication with your plugin but i'm getting this error when submitting the login or signup form . 

Any idea ? 

TypeError: Cannot read property 'token' of undefined
    at Object.angular.module.constant.provider.factory.Shared.setToken (satellizer.js:301)
    at Object.angular.module.constant.provider.config.$get.$auth.setToken (satellizer.js:245)
    at signupController.js:6
    at angular.js:14634

**Comment by jdrouet** [comment]
Hi !

Can you show me your satellizer/loopbackauth configurations and your signup controller ?

**Comment by jdrouet** [comment]
And waht is the answer of the server ? It looks like it doesn't give back the access_token

**Comment by thugyac** [comment]
hi jdrouet, 

Thanks for your reply. Yes i dont get the accesToken . 
There is my signup controller  : 

var app = angular.module('myapp');
app.controller('signupController', function($scope, $location, $auth, toastr) {
    $scope.signup = function() {
      $auth.signup($scope.user)
        .then(function(response) {
          $auth.setToken(response);
          $location.path('/');
          toastr.info('You have successfully created a new account and have been signed-in');
        })
        .catch(function(response) {
          toastr.error(response.data.message);
        });
    };
});

**Comment by jdrouet** [comment]
And what do you get ?

**Comment by thugyac** [comment]
When i run a console.log of the "response" I only get my html template.

**Comment by jdrouet** [comment]
What's your satellizer configuration ? How is configured loopback ?

**Comment by thugyac** [comment]
All my my app is on webserver listening on localhost, and i have a node.js who's listenning http://127.0.0.1:3000 and for satellizer follow your instruction . 
- In my app.js 
  
  $authProvider.facebook({
      clientId: 'fb-client-id'
    });
  
    $authProvider.google({
      clientId: 'google-client-id'
    });
- My loopback server.js 

var loopback = require('loopback');
var boot = require('loopback-boot');

var app = module.exports = loopback();

app.start = function() {
  // start the web server
  return app.listen(function() {
    app.emit('started');
    console.log('Web server listening at: %s', app.get('url'));
  });
};

// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname, function(err) {
  if (err) throw err;

  // start the server if `$ node server.js`
  if (require.main === module)
    app.start();
});

**Comment by jdrouet** [comment]
For loopback you have to follow the example (https://github.com/moooink/loopback-component-satellizer/tree/master/example)
- Add this module to your package.jon
- Add your configuration to you component-config.json (https://github.com/moooink/loopback-component-satellizer/blob/master/example/server/component-config.json)

For Angular you have to set the url of the server. In the example, you'll have the following configuration

``` javascript
.config(function($authProvider) {
  // Here is to avoid conflict between LoopBackAuth and Satellizer
  $authProvider.authHeader = 'x-access-token';
  $authProvider.authToken = null;

  var host = window.location.origin || window.location.protocol + '//' + window.location.host;

  $authProvider.facebook({
    clientId: 'HERE IS YOUR FACEBOOK CLIENT ID',
    url: host + '/api/accounts/facebook' , // <= this is the url
    scope: ['email'],
    scopeDelimiter: ',',
    redirectUri: host + '/',
    requiredUrlParams: ['display'],
    });
  $authProvider.google({
    clientId: 'HERE IS YOUR GOOGLE CLIENT ID',
    url: host + '/api/accounts/google' // <= this is the url
  });
);
```

**Comment by thugyac** [comment]
Ok thank you i will do that and get back to you . 

Thx u jdrouet

**Comment by jdrouet** [comment]
You're wellcome

**Comment by thugyac** [comment]
Salut Jdrouet, 

J'ai vu que tu vivais en France ça tombe bien je parle Français ;-) . 
Bon j'ai suivi tes instructions à la lettre, j'ai la même configuration au niveau server.js et j'ai bien rajouter le component-config.json avec les id et key qui vont bien. 

D'un autre coté j'ai rajouté dans le app.js routes pour chaque provider, etc.. mais le problème persiste. 

J'ai toujours l'ereur suivante: Error: Expecting a token named "token" but instead got: "HTML TEMPLATE", donc il attend un token en réponse mais je reçois toute la page html ...

**Comment by jdrouet** [comment]
As-tu été voir dans l'explorer si les routes étaient bien définies ? As tu essayé de faire un curl sur les routes en question ?

**Comment by thugyac** [comment]
Euh, dans l'explorer je ne vois pas les routes concernant google et facebook mais quand je fais un curl les urls existent mais je reçois une 401 ,
[root@localhost tia]# curl -I http://127.0.0.1:3000/api/accounts/facebook
HTTP/1.1 401 Unauthorized
X-Powered-By: Express
Vary: Origin, Accept-Encoding
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Content-Length: 774
ETag: W/"306-hCRLiKmTWmr5jGdUBFI10A"
Date: Sun, 18 Oct 2015 09:18:24 GMT
Connection: keep-alive

**Comment by jdrouet** [comment]
T'as ajouté les acls ?

**Comment by thugyac** [comment]
Oui les ACLs sont bien ajouté , 

  "acls": [
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$unauthenticated",
      "permission": "ALLOW",
      "property": "facebook"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$unauthenticated",
      "permission": "ALLOW",
      "property": "google"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$unauthenticated",
      "permission": "ALLOW",
      "property": "twitter"
    }
  ],

Alors quand j'essaye de m'inscrire, la requête POST du formulaire demande cette URL , 
Request URL:http://127.0.0.1/auth/signup , ne devrais-je pas avoir plutôt une url de ce type http://127.0.0.1:3000/api/accounts/ ?

**Comment by jdrouet** [comment]
Ça dépend, le modèle auquel tu attaches l'authentification et son plural
sont quoi ?

**Comment by thugyac** [comment]
J'ai pas compris ta demande...

**Comment by doktordirk** [comment]
don'T understand half of it, but be aware that most will user the model 'user' and not  'Account': so better make sure you use either or, and not both mixed (unless you know what you do)
